---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nihemart/nihemart_v2
    - /usr/bin/pnpm install
    - /usr/bin/pnpm run build
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH # If you are using a custom server.js
