// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxsbnejbjoqxiywrerjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4c2JuZWpiam9xeGl5d3JlcmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDkxMDYsImV4cCI6MjA3MDQyNTEwNn0.IR-cLuij3jc9Yl_9jaj77TmpOJfUiyi81JeGLnMvWow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});